### ISSUE TITLE
outpainting video is very blurry

### ISSUE THREAD

**Issue by ioir123ju** [MCG-NJU/BIVDiff#1]
source
![source_video](https://github.com/MCG-NJU/BIVDiff/assets/14951957/99db9ad8-3625-424f-b130-5f87c60ec984)
idm
![video_by_idm](https://github.com/MCG-NJU/BIVDiff/assets/14951957/5255e21d-1697-4ac3-a29a-2a355af883f8)
mask
![masked_video](https://github.com/MCG-NJU/BIVDiff/assets/14951957/2052bbb2-1625-42eb-aba9-ee5f3b58036b)
bivdiff
![video_by_bivdiff](https://github.com/MCG-NJU/BIVDiff/assets/14951957/0b7ec8d6-fe6e-495e-b1ad-7aa94eb692f9)

**Comment by ShiFengyuan1999** [comment]
Hi @ioir123ju,
The blurry results may come from poor frames by IDM. There are big differences among the areas completed by IDM in each frame. To make these particularly different images temporally consistent, VDM may tend to generate blurry videos.

Video generated by IDM
![idm](https://github.com/MCG-NJU/BIVDiff/assets/36044601/c70d2233-1299-41c4-be93-9239c887283d)

**Comment by ioir123ju** [comment]
> Hi @ioir123ju, The blurry results may come from poor frames by IDM. There are big differences among the areas completed by IDM in each frame. To make these particularly different images temporally consistent, VDM may tend to generate blurry videos.
> 
> Video generated by IDM ![idm](https://private-user-images.githubusercontent.com/36044601/344383192-c70d2233-1299-41c4-be93-9239c887283d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3OTc0MDIsIm5iZiI6MTcxOTc5NzEwMiwicGF0aCI6Ii8zNjA0NDYwMS8zNDQzODMxOTItYzcwZDIyMzMtMTI5OS00MWM0LWJlOTMtOTIzOWM4ODcyODNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDAxMjUwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExNTczNmExZmI4ODViZmIxZDQzOWU3YTEzYWZkYjE0MTgyZTczNmQ0NjgwNWVjYTIyMTg2YWI4MTliMmZjYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6O_6D82mAQusr247lu3Lr1BFEjv-zwYE1FWG8Q4HUWg)

If I generate a decent outpainting images in ComfyUI, can I directly use VDM for smoothing?Or I can also share my workflow with you; it can generate excellent outpainting images.
![image](https://github.com/MCG-NJU/BIVDiff/assets/14951957/4bddf920-f0fa-4cba-8b24-d9a07a73096c)

**Comment by ShiFengyuan1999** [comment]
@ioir123ju If there are no big differences (in structures, objects, and so on) among the filled areas of the outpainting images by ComfyUI, you can use VDM for smoothing and get better results.

**Comment by ioir123ju** [comment]
> @ioir123ju If there are no big differences (in structures, objects, and so on) among the filled areas of the outpainting images by ComfyUI, you can use VDM for smoothing and get better results.

I'm not sure where I went wrong; the generated image is just noise.
![image](https://github.com/MCG-NJU/BIVDiff/assets/14951957/c0f0892f-1a92-409b-bc95-7191de079edd)

**Comment by ShiFengyuan1999** [comment]
@ioir123ju Did you remove the codes of Mixed Inversion. Once you get the videos by IDM, you should first invert the video to noise latents by Mixed Inversion, then use VDM for temporal smoothing.
