### ISSUE TITLE
Training code.

### ISSUE THREAD

**Issue by quangtrungtruong** [MCG-NJU/BIVDiff#4]
Thank you for the wonderful work! I wonder when the training code is released. I like to reproduce the method with my data from scratch.

**Comment by ShiFengyuan1999** [comment]
Hi @quangtrungtruong, our BIVDiff is a training-free framework for video synthesis by bridging image and video diffusion models. We use open-sourced image and video models in the community (e.g., Instruct Pix2Pix and VidRD). You can replace these models with your own trained models or other open-sourced models.
